package.json
src/pages/index.tsx
yarn.lock

Package 수정

---

.prettierrc

* develop branch prettierrc fix

Fix:prettierrc fix

---

src/lib/Token.tsx

-  토큰 유효기한을 localStorage에 넣어서 토큰 리프레쉬 작업을 하려는데 localStorage key로 지정해 줄 상수가 없음
```ts
export const expiredAt = 'Gauth-expiredAt';
```

Feat: localstorage 토큰 유효기한 key를 상수로 지정

---

src/components/SignUpPage/style.ts

* 회원가입 이미지 업로드시 회원가입 버튼 위치가 바뀌는 이슈 발견
* 이미지 업로드 컴포넌트 디자인 수정

Fix:signup style fix

---

package.json
yarn.lock

* 서비스 목록 & 마이 프로필 페이지에서 서비스 리스트에 들어가 Open Graph 이미지 필요.
*  @microlink/mql 설치
* [microlink](https://microlink.io/)

Add:@microlink/cli

---

src/components/LoginPage/index.tsx
src/components/LoginPage/style.ts

- pull 받아 login 화면으로 넘어오니 이상한 점이 보였다.
- "@gsm.hs.kr"은 오른쪽으로 살짝 위치해있고 로그인 시 이상한 url로 이동한다...
- querystring을 받았는지에 대한 조건을 수정하였다.
- input의 길이를 늘렸다.
- @jjaejjae12 랑 테스트를 해봤으며 이제는 이상한 점이 안 보인다.

Fix loginpage query check and style

---

src/components/ServiceList/ListItem.tsx
src/components/ServiceList/ListTable.tsx
src/components/ServiceList/index.tsx
src/components/ServiceList/style.ts
src/pages/servicelist.tsx

서비스 리스트 페이지 추가
* 서비스 리스트 페이지 퍼블리싱 
* 전체 서비스 받아오는 기능 추가

Add ServisList Page 

---

src/components/InstructionPage/index.tsx
src/components/InstructionPage/style.ts
src/lib/InstructionUrl.ts
src/pages/[notion].tsx
src/pages/instruction.tsx

- 설명 페이지가 필요함
-  Notion 페이지를 써야 됨
- use react-notion lib
- 서비스 페이지 제작
- 좀 지났어도 봐줘잉..

Add Instruction Page

---

src/components/SignUpPage/index.tsx

비밀번호 찾기 기능이 구현되지않아서 비밀번호찾기를 누를때 보여줄 toast추가 필요
* 비밀번호 찾기버튼에 toast문구 추가

Fix:비밀번호 찾기 버튼 수정

---

src/components/MyServiceList/ModifyMyService.tsx
src/components/MyServiceList/style.ts

서비스 수정 모달창을 띄우고 배경클릭시 모달닫기가 되지않는 버그 발견
* 스타일 수정
* 추가로 필요없는 import 제거

Fix:필요업는import삭제&스타일 수정

---

src/components/MyServiceList/style.ts
src/components/ServiceList/style.ts

서비스 이미지가 잘리는 버그 발견
* 서비스 이미지 스타일 수정

Fix:서비스 이미지 스타일 수정

---

src/components/SignUpPage/style.ts
src/components/VerifyEmail/style.ts

회원가입 페이지가 모바일 화면에서 깨지는 현상 발생
회원가입 페이지에 반응형 추가

update signup page responsive

---

src/components/SignUpPage/index.tsx

비밀번호 유효섬 검사가 제대로 작동하지 않음
비밀번호 유효성 정규식 추가

Add signup password regexp

---

src/components/SignUpPage/index.tsx

비밀번호를 입력할 때 일부 특수문자가 입력이 안되는 경우가 있어서 정규식을 수정했습니다

🔀비밀번호 정규식 수정

---

src/components/LoginPage/index.tsx
src/components/SignUpPage/index.tsx

선생님들 계정도 로그인 할 수 있게 이메일 정규식을 수정했습니다

🔀로그인 form 이메일 정규식 수정

---

src/components/SignUpPage/index.tsx

email요청을 여러번 할 수 있어 image 업로드도 여러번 생기는 문제 발생
email요청에 loading 기능 추가

🔀 다중 이메일 요청 방지 기능 추가

---

src/components/LoginPage/index.tsx
src/components/SignUpPage/index.tsx

🔀 회원가입 이메일 최대 길이 삭제

---

package.json
src/api/index.ts
yarn.lock

오래된 라이브러리 발견
* add yarn-upgrade-all
* use yarn-upgrade-all

🔀 Update denpendency 

---

src/components/LoginPage/index.tsx
src/components/SignUpPage/index.tsx

회원가입 페이지에서 로그인 페이지로 이동할 때 query 처리가 제대로 되지 않아 수정했습니다

🔀로그인 페이지 query 처리 수정

---

next.config.js
src/components/ServiceList/ListItem.tsx
src/components/ServiceList/ListTable.tsx
src/components/ServiceList/index.tsx
src/components/ServiceList/style.ts
src/components/Sidebar/index.tsx
src/components/Sidebar/style.ts

새 디자인이 나와서 변경해주었다
* 사이드바 디자인 약간 수정

🔀 메인페이지 새 스타일 적용

---

src/components/NewSignIn/index.tsx
src/components/common/Auth/NewPasswordCommon.tsx
src/components/common/Input/index.tsx

errors message보기가 힘든것 같아서 문구를 추가 해 주었다
걍 토스트 추가 할까?

🔀 Input errors message 추가

---

src/components/NewFindPsw/NewPassword.tsx
src/components/NewSignIn/index.tsx
src/components/NewSignUp/Privacy.tsx
src/components/NewSignUp/Success.tsx
src/components/common/Auth/NewPasswordCommon.tsx
src/components/common/Auth/SearchEmail.tsx
src/components/common/Auth/VerifyEmail.tsx
src/hooks/useResetModal.ts

어스 로그인 상태에서 url 이동시 어스 url을 삭제되어 어스 로그인이 아닌 그냥 로그인 페이지로 넘어가지는 문제 발견
어스 url을 있을때 다음 url로 이동시키는 훅 추가

🔀 모달 이동 훅 추가

---

src/api/TokenManger.ts
src/api/index.ts
src/components/NewFindPsw/index.tsx
src/components/NewSignIn/index.tsx
src/components/NewSignIn/style.ts
src/components/NewSignUp/index.tsx
src/hooks/useAutoLogin.ts
src/types/TokenMangerType.ts

만료된 토큰과 함꼐 어스 로그인시 발생하는 이슈
토큰이 있어도 메인 페이지로 가지 않는 이슈와
자동 로그인 안된다는 이슈 발견
* 토큰 재발급 로직 수정
* 자동 로그인 기능 추가

🔀 자동 로그인 기능 추가

---

src/hooks/useFetch.ts
src/types/hooks/useFetch.ts

useFetch 만들기
``` ts
const {
fetch,	// (body?: any) => Promise<any>
data,	// Promise<T>
isLoading		// boolean
} = useFetch({
url: string
method: Method
onSuccess: (data) => void	// optional
onFailure?: (e: unknown) => void | Promise<void>;	// optional
successMessage?: string;	// optional
errorMessage?: { [status: number]: string };	// optional
})
```

🔀 useFetch hook 추가

---

src/components/MyServiceList/Delete/style.ts
src/components/MyServiceList/Modify/style.ts
src/components/MyServiceList/style.ts
src/components/Sidebar/style.ts
src/components/common/Input/index.tsx
src/components/common/Input/style.ts

내 서비스 리스트 반응형시 가장 아래 서비스가 가려지는 이슈 발견
Input cursor props name 이슈
* 서비스 리스트 스타일 수정
* input cursor props name 수정
* 애니메이션 추가

🔀 내 서비스 리스트 스타일 수정

---

src/components/NewService/InfoModal/index.tsx
src/components/NewService/InfoModal/style.ts
src/components/NewService/index.tsx

서비스 생성시 하나의 입력 박스에 에러가 나면 다른 입력 박스에 에러 문구가 나오는 버그 발견
* 에러 메시지 발생 로직 수정
* 포탈 수정

🔀 서비스 생성시 에러 메시지 중복 버그 수정

---

src/pages/_app.tsx

가우스 불편해요
지어스 편안
@googoo81  너도 pr 참여해 ㅎ

🔀 GAuth title 변경

---

src/components/NewSignIn/index.tsx

로그인할 때 유저 정보가 없어도 에러 핸들링이 되자 않는 이슈가 발생하였습니다.
로그인 요청에서 에러 발생시 에러 코드에 맞는 에러 메시지 상태 값을 업데이트 하는 코드 추가

🔀 에러 문구 추가

---

src/components/MyServiceList/Modify/index.tsx

서비스 수정 요청에 redirectUri값 할당이 되고있지 않아서 수정시 이슈가 발생
서비스 수정 요청문에 redirectUri값을 할당해주었다.

🔀 서비스 수정 요청에 redirectUri값 할당

---

src/components/common/StuListFilter/style.ts

StuListFilter 컴포넌트의 세로가 디자인과 다른 이슈
- StuListFilter 컴포넌트의 디자인 수정

🔀 가입 수락된 유저 필터 스타일 수정

---

src/components/MyServiceList/ListItem.tsx
src/components/MyServiceList/style.ts

내가 등록한 서비스 수정 UI 변경
변경된 디자인으로 UI를 수정했습니다.

🔀 내가 등록한 서비스 수정 UI 변경

---

src/components/MyServiceList/ListItem.tsx

서비스를 수정할 때 서비스 창 클릭으로 수정이 불가하고 서비스 수정하기 글씨를 눌러야 수정이 가능함
서비스 창을 클릭해 서비스를 수정할 수 있게 코드를 변경함
서비스 수정하기 글씨를 클릭했을 때 수정하는 것이 아닌 서비스 창을 클릭했을 때 수정할 수 있도록 코드 변경

🔀 내 서비스를 서비스 창 클릭으로 수정하기

---

src/components/common/Auth/VerifyEmail.tsx

🔀 이메일 인증 어법 수정

---

src/components/MyProfilePage/index.tsx

두 제목의 어법이 일치하지 않음
서비스 타이틀을 수정했습니다.

♻️ Refactor 서비스 타이틀 수정

---

public/svg/CloseIcon.tsx
public/svg/OpenIcon.tsx

로그인 화면의 비밀번호의 visible을 조절하는 버튼의 크기가 지나치게 큼
visible을 조절하는 버튼의 크기를 수정했습니다.

svg size modify

---

src/components/MyProfilePage/style.ts
src/components/MyServiceList/EmptyList.tsx
src/components/MyServiceList/style.ts

등록한 서비스가 없을 때 UI가 변경됨.
등록한 서비스가 없을 때 UI를 수정했습니다.

🔀 등록한 서비스가 없을 때 UI 변경

---

src/components/MyServiceList/Modify/style.ts

서비스 수정 모달 반응형 미흡
서비스 수정 모달 반응형을 수정했습니다.

🔀 서비스 수정 반응형

---

src/components/common/Auth/SearchEmail.tsx

회원가입 페이지 텍스트 수정
가입하실 이메일로 텍스트를 변경함

🔀 회원가입 텍스트 수정

---

src/components/common/Auth/NewPasswordCommon.tsx

비밀번호 확인 칸에서 글자가 5개밖에 입력되지 않음
maxlength value를 변경함

🔀 비밀번호 확인칸 오류 수정

---

src/components/common/Auth/NewPasswordCommon.tsx

비밀번호 확인칸에서 5글자 밖에 입력되지 않았음
maxLength value를 72로 수정

 🔀 비밀번호 재입력 오류 수정

---

src/components/MyServiceList/Modify/index.tsx

maxLength가 0으로 설정 되어있어서 url 수정이 안됨
maxLength를 254로 변경하였다

🔀 서비스 수정하기 maxLength 수정

---

src/components/MyProfilePage/Profile.tsx

프로필 이미지 업로드 기능을 수정하였습니다.
이미지 업로드 시에 이미지 링크를 받고 이미지 링크를 user로 보내며 user에 저장되어있는 링크를 받아와 출력하도록 함수를 추가 및 변경하였습니다.

🔀 프로필 이미지 업로드 기능 수정

---

src/components/MyProfilePage/Profile.tsx
src/components/MyProfilePage/style.ts

기능 추가 및 디자인 수정
프로필 이미지를 제거하는 기능을 추가하고, 프로필 이미지 디자인을 수정하였습니다.

🔀프로필 이미지 제거기능 추가 및 디자인 변경

---

src/components/MyProfilePage/Profile.tsx
src/components/MyProfilePage/style.ts
src/components/NewPsw/index.tsx
src/components/NewPsw/style.ts
src/components/common/Auth/ChangePasswordCommon.tsx
src/pages/changepsw.tsx

기존엔 비밀번호 찾기를 통한 변경만 가능했다
기존 비밀번호와 새 비밀번호를 입력해 비밀번호 변경이 가능하다

🔀비밀번호 변경 기능 추가

---

src/components/SignIn/index.tsx

버튼을 많이 클릭하면 요청이 여러번 전송됐다
debounce를 구현하였습니다
resolved: #126

🔀 로그인 페이지 버튼 debounce 처리

---

src/components/SignIn/HealthCheck/index.tsx
src/components/SignIn/HealthCheck/style.ts
src/components/SignIn/index.tsx
src/components/SignUp/Success.tsx
src/components/SignUp/style.ts
src/components/common/Detail/index.tsx
src/components/common/Detail/style.ts

서버가 꺼져있을 때 사용자에게 알려주는 헬스체크 창을 만들었습니다

🔀 health check 기능 추가

---

src/Atom/Atoms.tsx
src/components/common/Auth/SearchEmail.tsx

회원가입시 중복된 이메일인지 아닌지를 구별하는 기능을 추가하였습니다.
- '다음' 버튼을 눌렀을 때 중복된 이메일 이라면 input아래에서 알려주도록 제작하였습니다.

🔀중복된 이메일 검사 기능 추가

---

src/Atom/Atoms.tsx
src/components/SignUp/Profile.tsx
src/components/SignUp/StudentName.tsx
src/components/SignUp/StudentNumber.tsx
src/components/SignUp/index.tsx
src/components/common/Auth/ChangePasswordCommon.tsx
src/types/NumberForm.ts

> v2 signup api를 사용하여 학번과 이름을 받을 수 있도록 했습니다
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!

🔀 회원가입 시 학번, 이름 받기

---

src/components/MyProfilePage/Profile.tsx

변경을 위해 변경 혹은 삭제 버튼을 누르기 위해 마우스 포인터를 움직일 때 깜빡임이 심하여 이를 해결하게 되었습니다.
Resolves: #223 
setState 함수를 마우스 올릴시 현재 boolean값의 반대값으로 반환시키는 형태에서 false로 반환시키는 함수로 변경하였습니다.

🔀 프로필 이미지 수정 시 깜빡임 최소화

---

src/pages/stulist.tsx

stulist 페이지에 seoconfig를 추가하였습니다
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!

🔀 stulist seoconfig 추가
