GSM-MSG/GAuth-FrontEnd

src/styles/GlobalStyle.tsx
- GlobalStyle에 border-box를 안 넣어서 padding이나 margin을 넣으면 불필요하게 길이를 조정해야되는 코드가 발생
- merge 되면 각 branch에서 pull 받은 후 수정된 global css에 맞게 style을 수정
- develop branch는 @jjaejjae12 의 작업물만 완료되어있어서 @jjaejjae12 가 수정
=> Style: GlobalStyle 수정

src/lib/API.tsx
- oauth 로그인 시 "예기치 못한..." toast가 뜨는 현상
- 회원가입 도중 이메일 인증하지 않고 진행할 시 로그인 페이지로 넘어가는 현상
- login 페이지에서는 querystring과 관계없이 token 작업을 무시하도록 수정
- 이메일 인증 도중 발생한 401은 refresh 작업을 무시하도록 수정
=> Fix: refresh 예외 상황에 oauth 로그인 추가

src/components/LoginPage/index.tsx, src/components/LoginPage/style.ts
- email input에서 "@gsm.hs.kr"를 클릭(터치)하면 아무 반응이 없음
- 다양한 서비스명의 길이에 맞는 반응형 Login Form Title(Gauth 계정으로...)이 필요
- ["@gsm.hs.kr"를 투명한 배경인 input 뒤에 위치](https://github.com/GSM-MSG/GAUTH-frontend/commit/83c2ee023e3fc210be2e209e7f290066f7a3609c)
- [Login Form Title에 반응형 추가](https://github.com/GSM-MSG/GAUTH-frontend/commit/0c4a11a6ca594a2505d2ba0023bb9b883a4b96ac)
=> style: @gsm.hs.kr 위에 input이 올라가도록 수정

src/components/LoginPage/index.tsx
선생님 계정은 이메일 길이가 자유로워 maxLength를 삭제합니다
=> 🔀로그인 form에서 이메일 maxLength 삭제

src/components/LoginPage/index.tsx, src/components/LoginPage/style.ts, src/components/SignUpPage/index.tsx, src/components/SignUpPage/style.ts, src/lib/OauthQuery.ts
oauth 로그인 페이지에서 회원가입 페이지로 간 후 로그인 페이지로 가면 oauth 로그인이 아닌 gauth 사이트 로그인으로 바뀌는데 oauth 로그인 페이지로 가는게 자연스럽다고 생각하여 수정했습니다.
- 로그인 페이지에서 query(client_id, redirect_uri)가 존재하면 회원가입 페이지로 이동 시 query를 담아가고
회원가입 페이지에서 query가 존재하면 로그인 페이지로 이동 시 query를 담도록 수정했습니다.
uri에 query가 보이지 않도록 할까요? uri에 query가 있으면 지저분한 것 같긴 합니다
=> 🔀 로그인 페이지 라우팅 방식 수정

src/components/common/Portal/index.tsx
포탈컴포넌트에서 자식 컴포넌트를 눌러도 포탈 컴포넌트가 닫히는 버그 발생
* 자식 컴포넌트 이벤트 발생시 stopPropagation 추가
=> 🔀 Portal Add stopPropagation

src/components/NewSignIn/index.tsx, src/components/common/Auth/NewPasswordCommon.tsx, src/components/common/Input/index.tsx, src/components/common/Input/style.ts
비밀번호 input type이 passowrd여서 입력하다 생각이 안나면 클라이언트가 곤란 해질수도 있다고 판단
* password 입력부분에 passwordcheck기능 추가
* common input props fixed에 react element타입 추가
=> 🔀 비밀번호 체크 기능 추가

src/components/MyServiceList/style.ts
러스트가 없을 때 유저에게 보여주는 컴포넌트의 반응형이 되어있지 않았다.
* 디자인 수정
=> 🔀 리스트 없음 컴포넌트 반응형 추가

src/components/InstructionPage/style.ts
설명페이지의 코드블럭이 어색해서 수정했습니다
- 코드블럭의 style을 수정했습니다
| 변경 전 | 변경 후 |
|---------|----------|
| ![image](https://user-images.githubusercontent.com/87346613/227814646-620d4018-b64f-4e84-bc8f-19ae030a73fa.png) | ![image](https://user-images.githubusercontent.com/87346613/227814700-ddc84e53-a7d9-477c-a4aa-3affc42d91ec.png) |
---
- 설명 페이지의 text의 반응형이 자연스럽게 보이도록 수정했습니다
이보다 더 나은 디자인이 있다고 생각하면 comment 남겨주세요!
=> 🔀설명 페이지의 코드블럭 디자인 수정

src/components/Sidebar/index.tsx
next13에서는 `<Link>` 태그만 써도 라우팅이 되지만 v12에서는 <Link> 태그만으로는 라우팅을 할 수가 없어서 오류가 발생했습니다.
`<Link>` 태그 안에 `<a>` 태그를 추가했습니다.
=> 🔀 Sidebar 라우팅 오류 수정

src/Atom/Atoms.tsx, src/components/common/StuListFilter/index.tsx, src/types/components/Sidebar.ts
- 어드민 페이지의 Stulist에서 학년/반을 선택하면 선택 해제가 되지 않았습니다.
- Stulist에서 전체 조회를 할 수 없었습니다.
- Stulist의 atom default 값을 변경했습니다.
- 학년/반 선택 해제 기능을 추가했습니다.
=> 🔀 Stulist 전체 조회 기능 추가

src/components/common/StuListFilter/style.ts
재학생, 졸업생, 선생님 유저 필터링의 위치가 왼쪽으로 치우쳐져 오른쪽 너비가 부각된다는 이슈가 있었음
보다시피 글자를 조금더 중앙으로 옮김
필터링 내부 패팅 크기가 달라짐
=> modify filtering location

src/components/SignIn/index.tsx
로그인 중일 때 로그인 버튼을 누르면 그대로 요청이 가서 낭비되는 상황 발생
요청 중일 때 로그인 버튼을 눌러도 재 요청을 막도록 수정
=> 🔀 로그인 요청 중일 때 재 요청 막는 로직 추가

src/components/Stulist/Header/index.tsx, src/components/common/StuListFilter/style.ts
알람 svg를 클릭했을 때 applicant로 이동이 안됐음
svg를 div로 한번 감쌌음
=> wrap alarm svg

src/components/MyServiceList/index.tsx
등록한 서비스가 없을 때에도 삭제 버튼이 존재함
내 서비스가 없을 땐 삭제 버튼이 존재하지 않게 수정했습니다
=> 🔀 등록한 서비스가 없을 때 삭제버튼 hide 처리

src/components/MyProfilePage/style.ts, src/components/MyServiceList/Modify/index.tsx
서비스명을 수정할 때 글자 수 초과시 빈 toast가 출력되는 이슈 존재
- 제한 글자 수를 초과할 때 출력 에러메시지를 추가했습니다.
=> 🔀 서비스명 수정에서 제한 글자 수 초과시 에러메시지 출력

src/components/SignIn/index.tsx, src/components/common/Auth/NewPasswordCommon.tsx, src/components/common/Auth/SearchEmail.tsx
이메일 앞부분에 '.'이 들어갔음
정규식을 수정하여 이메일 input value를 제한함
=> 🔀회원가입 이메일 input 정규식 변경

src/components/MyProfilePage/Profile.tsx
#191 
졸업생들은 학년, 반, 번호에 대한 정보가 없기때문에 null로 노출되는 점에 대해서 `졸업생`으로 표기되게끔 변경
=> 🐛 Fix null exception about PrivacySection at user profile

src/components/Stulist/AddUser/index.tsx
어드민이 회원가입을 요청한 회원을 승인할때 오류가 발생했습니다.
Resolves: #216
API 요청을 보낼 때 명세서에 따라 body의 userRole을 userRoleType으로 변경했습니다.
> 템플릿 체크리스트 말고도 추가적으로 필요한 체크리스트는 추가해주세요!
=> 🔀 회원승인 요청 body 수정

src/components/MyServiceList/Modify/Assignment/index.tsx, src/components/MyServiceList/Modify/CoWorkerModal/index.tsx, src/components/MyServiceList/Modify/CoWorkerModal/style.ts, src/components/MyServiceList/Modify/DeleteAssignment/index.tsx, src/components/MyServiceList/Modify/index.tsx, src/components/ServiceCo-WorkerList/Assignment/index.tsx, src/components/ServiceCo-WorkerList/index.tsx, src/components/ServiceCo-WorkerList/style.ts
공동작업자를 8명 이상 추가 시에는 공동작업자 목록에서 확인해야하는데 확인하는 목록 모달에서 삭제 혹은 소유자 위임을 하게 되면 오류가 뜨는 현상이 발생하여 이를 고치고, 학생 리스트디자인이 누가봐도 잘못되어 있었기에 디자인적 수정도 하게 되었습니다.
Resolves: #221
공동작업자 목록 모달에 유저의 Id로 설정할 수 있도록 관련 함수를 인수로 보냈고, 잘못 사용되고있는 스타일 컴포넌트를 삭제하였습니다.
유저를 설정할 수 있도록 관련 함수를 보내면 간단하게 해결할 수 있었던 것을, 컴포넌트를 불러오는 데 문제가 있다고 생각하며 잘못된 접근 방식으로 이슈를 해결하려고 하여 골머리를 썩혔습니다.
=> 🔀 공동작업자 기능 및 디자인적 오류 해결
